on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: ["linux"]
        goarch: ["386"]
    env:
      CGO_ENABLED: 1
    steps:
      - uses: actions/checkout@v2

      - name: Set APP_VERSION env
        run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
      - name: Set BUILD_TIME env
        run: echo BUILD_TIME=$(date --iso-8601=seconds) >> ${GITHUB_ENV}

      - uses: wangyoucao577/go-release-action@v1.52
        with:
          pre_command: |
            sudo apt-get -y update
            sudo apt-get install -y gcc-multilib
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "1.23"
          md5sum: false
          overwrite: true
          project_path: "./"
          ldflags: -X "github.com/et-nik/metamod-go-example/main.Version=${{ env.APP_VERSION }}" -X "github.com/et-nik/metamod-go-example/main.BuildDate=${{ env.BUILD_TIME }}"
          build_flags: -o example.so -buildvcs=false -buildmode=c-shared
          binary_name: "example.so"
          extra_files: README.md